### ISSUE TITLE
Can't define multiple params for every other column

### ISSUE THREAD

**Issue by rediaz111** [kalekundert/wellmap#20]
Hi Kale,
I've scaled up my assay from a 96w plate to a 384w. Unfortunately, the multichannel pipette is spaced such that every other well is loaded. I'm trying to set it up so that each row is a unique timepoint (A = 0, B = 15, etc), the rows also have a sample ID (A, B,..., F, = FL, G = Buffer), and there's a block for my standards in Row G.  

I'm struggling to define rows for every other column once I've used the [well.'A1,B3,...,F23'] format. 

I hope this explanation makes sense. I've attached a screenshot and the code below. Do you have any suggestions for how to address this issue?

Thanks for your time!

![Screen Shot 2021-09-30 at 17 02 14](https://user-images.githubusercontent.com/32281616/135547233-3746148c-23e6-40fb-b781-d2b52e970a96.png)

[plate.1.row]
A.time = 0
B.time = 15
C.time = 30
D.time = 45
E.time = 60
F.time = 90

[plate.1.well.'A1,B3,...,F23']
sample = 'AMCase Catalytic Domain'

[plate.1.well.'G1,G3,...,G23']
sample = 'Buffer'

[plate.1.block.1x1] 
'H1'.chitobiose = 100
'H3'.chitobiose = 50
'H5'.chitobiose = 25
'H7'.chitobiose = 12.5
'H9'.chitobiose = 6.25
'H11'.chitobiose = 0
'H13'.chitobiose = 100
'H15'.chitobiose = 50
'H17'.chitobiose = 25
'H19'.chitobiose = 12.5
'H21'.chitobiose = 6.25
'H23'.chitobiose = 0

**Comment by kalekundert** [comment]
Hey Roberto, good to hear from you!

Unfortunately, I don't think I quite understand what you're trying to do.  Is there anything in the even columns, and is the goal to have the rows mean something different in those columns?  You also mentioned that the rows have timepoints and sample IDs: how do those two attributes relate to each other (or is that not really relevant)?

**Comment by rediaz111** [comment]
There is something in the even columns, but that is a different technical replicate. My original assay set up involved using (1) 96w plate per technical replicate. Due to the plastic shortage, I switched to 384w plates. So now Plate 1 is the odd columns and Plate 2 is the even columns in the 384w format for rows A-H. Plates 3 and 4 would be odd and even columns for rows I-P, respectively.

Right now, I'm only running one experimental sample (which has timepoints) and the other 'sample' is a buffer control (no timepoints).
 
The previous 96w toml file looked like this:

```
[plate.1]
[plate.2]

[row]
'A,B,C,D,E,F'.sample = 'AMCase Catalytic Domain'
'G'.sample = 'Buffer'
A.time = 0
B.time = 15
C.time = 30
D.time = 45
E.time = 60
F.time = 90

```
<img width="494" alt="Screen Shot 2021-09-30 at 22 47 02" src="https://user-images.githubusercontent.com/32281616/135571742-3c464538-ce42-4b00-a981-b33ef0e4318b.png">

So I'm trying to convert my old 96w formatting into something compatible with alternating columns in a 384w layout. I would define entire blocks if I could read the entire plate at once, but I can't do that without there being significant lag time between replicates due to the experimental set up.

I hope this clarifies what I'm trying to do a bit more. I really appreciate your responsiveness!

**Comment by kalekundert** [comment]
Ah, I think I understand.  You don't want the time to be defined for the even columns, but you can't just do `''A1,A3,...,A23'.time = 0` etc. because wellmap complains about `A1` being defined more than once.  Is that right?

This really seems like a bug to me.  You should be able to include the same well in different patterns.  I'll have to look at the code to see if there's some reason for disallowing this that I'm forgetting right now, but it really doesn't seem right.

In the meantime, you can work around it by using `block` instead of `well` to define the sample name:
```toml
[plate.1.well]
'A1,A3,...,A23'.time = 0
'B1,B3,...,B23'.time = 15
'C1,C3,...,C23'.time = 30
'D1,D3,...,D23'.time = 45
'E1,E3,...,E23'.time = 60
'F1,F3,...,F23'.time = 90

[plate.1.block.1x6.'A1,A3,...,A23']
sample = 'AMCase Catalytic Domain'

[plate.1.well.'G1,G3,...,G23']
sample = 'Buffer'

[plate.1.block.1x1]
'H1'.chitobiose = 100
'H3'.chitobiose = 50
'H5'.chitobiose = 25
'H7'.chitobiose = 12.5
'H9'.chitobiose = 6.25
'H11'.chitobiose = 0
'H13'.chitobiose = 100
'H15'.chitobiose = 50
'H17'.chitobiose = 25
'H19'.chitobiose = 12.5
'H21'.chitobiose = 6.25
'H23'.chitobiose = 0
```
![blocks](https://user-images.githubusercontent.com/298132/135644027-c0679e88-dc48-47b3-9fd8-33b7fe2f38d2.png)

Alternatively, is it really a problem for the time to be defined for every column?  When the labels are merged with the data, any wells with no data will be dropped.  So usually it's ok to have labels defined for wells that aren't really part of the layout.

**Comment by kalekundert** [comment]
I just fixed the bug preventing multiple patterns from using the same well, so upgrade to version 3.0.1 and it shouldn't be necessary to work around that anymore.

**Comment by rediaz111** [comment]
<img width="1280" alt="Screen Shot 2021-10-01 at 12 05 38" src="https://user-images.githubusercontent.com/32281616/135688581-de970ecc-db55-42ee-87de-6ce093c513db.png">

It works beautifully now using this code:
```
[plate.1.well]
'A1,A3,...,A23'.time = 0
'B1,B3,...,B23'.time = 15
'C1,C3,...,C23'.time = 30
'D1,D3,...,D23'.time = 45
'E1,E3,...,E23'.time = 60
'F1,F3,...,F23'.time = 90

[plate.1.block.1x6]
'A1'.4MU_chitobiose = 117
'A3'.4MU_chitobiose = 78
'A5'.4MU_chitobiose = 52
'A7'.4MU_chitobiose = 35
'A9'.4MU_chitobiose = 23
'A11'.4MU_chitobiose = 15
'A13'.4MU_chitobiose = 10
'A15'.4MU_chitobiose = 7
'A17'.4MU_chitobiose = 5
'A19'.4MU_chitobiose = 3
'A21'.4MU_chitobiose = 2
'A23'.4MU_chitobiose = 0

[plate.1.well.'A1,B3,...,F23']
sample = 'AMCase Catalytic Domain'

[plate.1.well.'G1,G3,...,G23']
sample = 'Buffer'
```
Thanks!

**Comment by rediaz111** [comment]
Should I open a separate issue if I'm having trouble with meta.paths and path_guess?

**Comment by kalekundert** [comment]
Nice, glad it worked.  Go ahead and open a new issue; I'll close this one.
