### ISSUE TITLE
Add hyphen as shortcut in pattern syntax

### ISSUE THREAD

**Issue by FitzsimmonsCM** [kalekundert/wellmap#23]
Hyphens can be a shortcut for simple patterns. 

For example, at present if I want columns 1 to 6 I would write it like this:
`"1,2,...,6"`

But this could be written more succinctly in this format:
`"1-6"`

This hyphen syntax can naturally be combined with the comma syntax:
`"1-6, 9"`

**Comment by jpm92** [comment]
I agree with this idea. I actually have my own simpler implementation of this library and I use colons since they are more readable and understandable.

**Comment by kalekundert** [comment]
I'm definitely planning to add this feature.  I've been busy with other things recently, but I do hope to get to it soon.

Regarding `1-6` vs `1:6`, one substantial difference is that TOML allows hyphens (but not colons) to be used in unquoted keys.  So it's probably more convenient to use hyphens for this syntax.
